### ISSUE TITLE
Request to be co-maintainer

### ISSUE THREAD

**Issue by NewZeal** [mccrodp/message_private#13]
Hi There,

I'd like to be co-maintainer of this project.  My Drupal account is here: https://www.drupal.org/user/93571

Thanks

Kent

**Comment by mccrodp** [comment]
Awesome, done here and Drupal.org. Hope to catch up next week.

**Comment by mccrodp** [comment]
@NewZeal - Hey, tried to email you from Drupal.org, not sure if it got through. Please email when you get a chance for a chat about maintaining. Thanks! :)

**Comment by NewZeal** [comment]
Hi Paul,

Sorry not to get back.  I've had a busy week.. I've accepted the invitation
to the repo at github.  We can chat this week.

Kent

**Comment by mccrodp** [comment]
No problem, talk to you this week. Thanks
