### ISSUE TITLE
in view message_private Broken/missing handler

### ISSUE THREAD

**Issue by bender-r** [mccrodp/message_private#14]
Іn view message_private
inbox and sent pages

Filter criteria:
Broken/missing handler

![selection_009](https://cloud.githubusercontent.com/assets/5053296/24102385/760174b2-0d84-11e7-9267-8021083f7fe7.png)

![selection_010](https://cloud.githubusercontent.com/assets/5053296/24102418/8e653304-0d84-11e7-83d5-61ab05f42094.png)

Messages on pages /user/%/messages and /user/%/messages/sent are not duplicated, and correspond inbox and sent

**Comment by ZenImagine** [comment]
Same problem for me.
The "/admin/content/messages" view is also broken by "Message UI".

**Comment by NewZeal** [comment]
Handler fixed in version pushed to project: https://www.drupal.org/project/message_private

**Comment by ZenImagine** [comment]
Hello, I have done the update module but this error is always possible.

**Comment by NewZeal** [comment]
Once I get the git process sorted with Paul then this repo will be in sync with the Drupal repo.

**Comment by ZenImagine** [comment]
This works, but you must uninstall the module and reinstall it.
A similar problem makes the message module unusable :
https://www.drupal.org/node/2891680
Too bad this little bug is so long to correct.

**Comment by NewZeal** [comment]
A broken handler in a View does not make a module unusable.  Simply edit the view and remove the handler.  Then if you need to replace the handler choose one that is suitable.

**Comment by ZenImagine** [comment]
There is a similar problem with Message UI

**Comment by NewZeal** [comment]
Closing due to inactive.
