### ISSUE TITLE
No results behavior is empty

### ISSUE THREAD

**Issue by bender-r** [mccrodp/message_private#15]
On pages  /user/%/messages and /user/%/messages/sent, if there are no messages does not show **No results behavior** from view message_private

**Comment by bender-r** [comment]
log

> Location 	http://localhost:8000/admin/structure/views/view/message_private/preview/page_1?_wrapper_format=drupal_ajax
Referrer 	http://localhost:8000/admin/structure/views/view/message_private
Message 	Missing text format: basic_html.

Probably by default it is worth using **plain_text** format

**Comment by NewZeal** [comment]
I'm closing this issue because it has been here a while and the latest iteration of the module has a no results text .  If someone wants to reopen, please do.
