### ISSUE TITLE
Add reply button

### ISSUE THREAD

**Issue by bender-r** [mccrodp/message_private#16]
On the page with the message, add a reply button, with prepopulate fields **Subject** and **username**

**Comment by mccrodp** [comment]
Yep, that should be there, thanks for filing it. PRs are welcome! 😄

**Comment by mccrodp** [comment]
I think this is the same as this, it's just a case of using the "Reply" string or the one listed there: https://github.com/mccrodp/message_private/issues/12

**Comment by NewZeal** [comment]
There is a reply button but no prepopulate fields in place.

**Comment by NewZeal** [comment]
I'm closing this issue because it has been here a while and the latest iteration of the module has a reply button.  If someone wants to reopen, please do.

**Comment by sarbazx** [comment]
@NewZeal How to add reply button in view? I can't find it.
