### ISSUE TITLE
In view message_private replace the field Message text

### ISSUE THREAD

**Issue by bender-r** [mccrodp/message_private#17]
It is probably more correct to replace the field **Message: Message text** on the field **Message: Body**  with -> Rewrite results -> Trim this field....

**Comment by bendevos** [comment]
message txt appear empty in all views in my case . I needed to replace it with body...

**Comment by ZenImagine** [comment]
Same problem for me.
![capture du 2017-07-02 18-14-46](https://user-images.githubusercontent.com/29839861/27771615-71364816-5f52-11e7-9cc3-f7276786831e.png)

**Comment by mccrodp** [comment]
Thanks, PRs welcome as I don't have time for this module at the moment.

**Comment by NewZeal** [comment]
Message text replaced with body in version pushed to Drupal project: https://www.drupal.org/project/message_private
