### ISSUE TITLE
Exception ConfigDuplicateUUIDException on installing

### ISSUE THREAD

**Issue by stborchert** [mccrodp/message_private#19]
Hey.
When trying to install the latest version of the module I get the following error:
`Uncaught PHP Exception Drupal\Core\Config\ConfigDuplicateUUIDException: "Attempt to save a configuration entity 'message.private_message.default' with UUID '1ea8d842-7162-47da-b9a2-d526cd5ac3f0' when this entity already exists with UUID 'b0ea355d-5bfe-498a-bc24-39f27310d766'" at core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php line 339`.

This error happens, because in all config files the UUID still exists. For default config it is necessary to remove this (see https://www.drupal.org/docs/8/creating-custom-modules/include-default-configuration-in-your-drupal-8-module "Exporting configuration").

**Comment by ChristopheDeG** [comment]
Same issue here!

**Comment by mccrodp** [comment]
Just merged https://github.com/mccrodp/message_private/pull/20, please test and if working I'll push to Drupal.org. Thanks all.

**Comment by mccrodp** [comment]
If this is working (the latest PR), perhaps a new dev release on Drupal.org is required: https://github.com/mccrodp/message_private/issues/19 Working for you, @NewZeal?

**Comment by mccrodp** [comment]
Just pushed this to Drupal.org, please re-open if error still persists.

**Comment by ChristopheDeG** [comment]
Hi,

When trying to send a private message, I get the following error:

Type: message
Location: /message/add/private_message
InvalidArgumentException: Unable to get a value with a non-numeric delta in a list. in Drupal\Core\TypedData\Plugin\DataType\ItemList->get() (regel 98 van /home/dceh1/www/core/lib/Drupal/Core/TypedData/Plugin/DataType/ItemList.php).

Type: php
Location: /message/add/private_message
Drupal\Core\Entity\EntityStorageException: Unable to get a value with a non-numeric delta in a list. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (regel 777 van /home/dceh1/www/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
