### ISSUE TITLE
Does Message Private support migration?

### ISSUE THREAD

**Issue by dev-code-davis** [mccrodp/message_private#21]
Hi, I'm interesting in migrating a D6 -> D8 site. The D6 version implemented [privatemsg](https://www.drupal.org/project/privatemsg) module (which doesn't have D8 version). And I'm interested in migrating all the previous messages to this module. So the question is - does this module work with Drupal migration_tools, migration_plus, etc.? Has anyone tried some migration works?

**Comment by mccrodp** [comment]
Hey. Not at the moment, it would be nice alright. PRs welcome :)

**Comment by dev-code-davis** [comment]
@mccrodp Heh, actually it seems that migration is working with core migrate module and migrate tools, migrate plus additions. The module is based on Contact Storage and thus implements contact_message entity which can be migrated quite easily.

If anyone is interested in some snippets:
YML - https://gist.github.com/Gugols/0c5a593d9666183c463c54d095464956
PHP (Ugly and just experimenting migrating into our slightly modified Migrate Private module) - https://gist.github.com/Gugols/6181187193f62556eedd24fd8032a195

**Comment by mccrodp** [comment]
That's great, if anything can be contributed back to Message Private, feel free to make a PR. Cheers.
