### ISSUE TITLE
Create Message threading

### ISSUE THREAD

**Issue by NewZeal** [mccrodp/message_private#28]
Currently message_private works on a per message basis.  You send a message to someone and the other person can send a message back to you.  You can send and receive messages to other people and all messages appear in date order in your inBox.

I'm working on a module that integrates with private_message to put messages into threads.  This is similar to the behaviour of the privatemsg module of yore.  It works as follows:

User can start a new conversation (thread), give it a title (e.g. organize Drupal meetup) and nominate a number of people to belong to it (participants).  Once created,  user sends a message.  The message adopts the participants from the conversation participants field (so no need to fill that out).  In the inBox, the user sees conversations (not messages).  The user can click on the conversation 'organize Drupal meetup' and they will see the thread of messages associated with that conversation.  At the top is a display of who is currently in the conversation and a link to reply to it.

A conversation can change participants (except usually the initiator cannot be removed) but individual messages within the conversation may have different participants, reflecting how the conversation has changed, and those messages will always retain the participants, meaning that a participant will never have access to a message in a conversation that didn't include them.

Since this is a separate module, and may have use with message stack modules other than private_message, it is not suitable for inclusion in this repo, hence I will probably host it separately.  I'm posting this because I have done a lot of work on it and it is relevant to work on private_message because it likely involves some changes.

**Comment by mccrodp** [comment]
>Since this is a separate module, and may have use with message stack modules other than private_message, it is not suitable for inclusion in this repo, hence I will probably host it separately. I'm posting this because I have done a lot of work on it and it is relevant to work on private_message because it likely involves some changes.

Do you mean `message_private` here? haha, many similar module names now. If so, sure, host elsewhere and link to it here, as it might be useful to others 😉

**Comment by ZenImagine** [comment]
I'm interested in a feature like this

**Comment by NewZeal** [comment]
I've created the module and posted it on github here:

https://github.com/NewZeal/message_thread

For it to work out of the box, you will need to patch the latest version of the private message module downloaded from this repository using:

https://gist.github.com/NewZeal/ca87d169b9c0e879a7bc1a1260c1d12e

**Comment by NewZeal** [comment]
I have been through the issues here and cannot see anything that clashes with any changes I have made to the message private module.  

The message thread module eliminates the need for the inbox in the message private module, however my diff does not remove it, yet, because there would need to be discussion around this.  If the message thread solution works and people don't see a need for a message private inbox then we get rid of it.

I think we should publish a version of the message private module here: https://www.drupal.org/project/message_private so I can publish the message thread here: https://www.drupal.org/project/message_thread and we can get community help in building the project.

**Comment by mccrodp** [comment]
Great job Kent, just to reiterate over emails publicly. Best to get the patch to Message Private required for Thread module in as a PR, for Message Private also to function individually, otherwise merging both of these into Message Private. See what makes the most sense. Thanks again.

**Comment by NewZeal** [comment]
How are we doing with that patch?  If we could have some code over at drupal.org https://www.drupal.org/project/message_private then I can publish my code there and we are more likely to get community contributions.  I'll put in a maintainer request.

**Comment by mccrodp** [comment]
Hey @NewZeal, just gave you permissions to administer releases over on Drupal.org, although we are a bit off that yet. You already had commit access and were a maintainer already. I'll do a quite look now, but no time to test unfortunately, so will just have to rely on code review.

**Comment by NewZeal** [comment]
Have you merged that patch?

**Comment by NewZeal** [comment]
I'll do some more testing on my local and also test private message by itself before committing anything.  First up will be an alpha1.

**Comment by mccrodp** [comment]
Just did code review on your PR.

**Comment by mccrodp** [comment]
If you think it is solid enough for an `alpha-1`, then fine, otherwise we leave as `dev` initially and see if you can get more testers, such as @ZenImagine above. Thanks all!

**Comment by NewZeal** [comment]
I had a question about newlines.  What do you mean by that?  Should there be a newline at the end of each file?

**Comment by mccrodp** [comment]
Most coding file types should have newline, GitHub will complain if not with a 🚫 symbol you will see that in PRs. Here's another link about it: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline?answertab=votes#tab-top

**Comment by NewZeal** [comment]
I pushed an initial alpha version to the project page: https://www.drupal.org/project/message_private  .  I suspect we'll get a better response from contributors with that in place.  

Is there any equivalence between the repo here at github and the one at Drupal or do we have to deploy  the two separately?

**Comment by NewZeal** [comment]
Module created and first release made: https://www.drupal.org/project/message_thread

**Comment by mccrodp** [comment]
@NewZeal, ok, great job on fixing all those bugs and getting a release out.

The way it usually works when people use GH for development, is that you work on a PR like: https://github.com/mccrodp/message_private/pull/29, once that PR gets merged (i.e. - after review and approved process, if any), then you have your `8.x.-1.x` branch on GH, you can push that to Drupal by adding `drupal` remote, then `git push drupal 8.x-1.x` to push to drupal `8.x-1.x` branch. 

Essentially you only push to drupal once stable, as the development in GH may not always be. Then you just tag and `git push drupal MY_TAG` and `git push origin MY_TAG` to get a release onto drupal and secondly keep GH in sync.

**Comment by NewZeal** [comment]
OK, so should I submit another PR?  I'm not sure if the last one was accepted or not.
Do I set up my repo so that it pushes to both Drupal and GH simultaneously?

**Comment by mccrodp** [comment]
No, you just commit updates to the same branch you submitted the PR to and
push to Github.

Yes, you setup your repo to have both remotes.

E.g. - `origin` will be GitHub and `drupal` will be drupal.org
Then you just `git push origin` and `git push drupal`

You do the same with tags:
`git push origin --tags`
`git push drupal --tags`

**Comment by NewZeal** [comment]
OK, thanks.  I've pushed to both remotes.  Closing this ticket now.
