### ISSUE TITLE
Use of undefined constant MESSAGE_PRIVATE_EMAIL_NOTIFICATIONS

### ISSUE THREAD

**Issue by SOLUTIONS-AT** [mccrodp/message_private#8]
Installed message_private on D8.1.3 and PHP 5.6.22

Reported error

Notice: Use of undefined constant MESSAGE_PRIVATE_EMAIL_NOTIFICATIONS - assumed 'MESSAGE_PRIVATE_EMAIL_NOTIFICATIONS' in Drupal\message_private\Form\SettingsForm->buildForm() (line 86 of /home/solution/public_html/my-domain.com/modules/message_private/src/Form/SettingsForm.php).

Location is reported as http://discrete.ch/admin/config/system/message-private
I think there should be an underscore between message and private, not a dash.

**Comment by mccrodp** [comment]
Thanks for reporting this. Yep, this is all just straight from D7, the constants and the Form itself require a make over and haven't been worked on really yet aside from getting the Form in the D8 structure.

**Comment by mccrodp** [comment]
Fixed after this commit. https://github.com/mccrodp/message_private/commit/7341aeced8b5dd8ded2d4378d864ead51b6738a7
